#!/usr/bin/env bash
# Initialises the project memory tree at .artefacts/memory/.
#
# Layout (see agentic-kit/templates/memory/SCHEMA.md):
#   .artefacts/MEMORY.md                 # L4 root summary
#   .artefacts/SESSION-STATE.md          # L1 hot state
#   .artefacts/memory/SCHEMA.md          # ontology
#   .artefacts/memory/preferences.md     # L3
#   .artefacts/memory/system.md          # L3
#   .artefacts/memory/projects.md        # L3
#   .artefacts/memory/decisions.md       # L3
#   .artefacts/memory/<YYYY-MM-DD>.md    # L2 (today's)
#   .artefacts/memory/index.jsonl        # L5 (created by memory-search.sh)
#
# Usage:
#   agentic-kit/tools/memory-init.sh                  # safe init (skips existing files)
#   agentic-kit/tools/memory-init.sh --force          # overwrite stubs from templates
#   agentic-kit/tools/memory-init.sh --migrate        # also import legacy SEMANTIC_MEMORY.md
#
# Run from project root.

set -euo pipefail

KIT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TPL_DIR="$KIT_DIR/templates/memory"
ARTEFACTS="${ARTEFACTS_DIR:-.artefacts}"
MEM_DIR="$ARTEFACTS/memory"
LEGACY_SEMANTIC="$ARTEFACTS/SEMANTIC_MEMORY.md"

FORCE=false
MIGRATE=false
for _arg in "$@"; do
  case "$_arg" in
    --force) FORCE=true ;;
    --migrate) MIGRATE=true ;;
    -h|--help) sed -n '2,21p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
  esac
done

mkdir -p "$ARTEFACTS" "$MEM_DIR"

copy_stub() {
  local src="$1" dst="$2"
  if [ -f "$dst" ] && ! $FORCE; then
    echo "  skip $dst (exists)"
    return
  fi
  cp "$src" "$dst"
  echo "  init $dst"
}

# L3 templates
for f in SCHEMA.md preferences.md system.md projects.md decisions.md; do
  copy_stub "$TPL_DIR/$f" "$MEM_DIR/$f"
done

# L1 SESSION-STATE.md
SESSION_STATE="$ARTEFACTS/SESSION-STATE.md"
if [ ! -f "$SESSION_STATE" ] || $FORCE; then
  cat > "$SESSION_STATE" <<'EOF'
# Session State (L1 — Hot)

_Updated by every agent on entry/exit. Pruned by `memory-rollover.sh` when stale (>24h)._

## Active feature
_(none — set by Vadavik or whoever starts the next feature)_

## Active agent
_(none)_

## In-flight decisions
_(append short bullets here as decisions are made; promoted to daily L2 by Zlydni)_

EOF
  echo "  init $SESSION_STATE"
else
  echo "  skip $SESSION_STATE (exists)"
fi

# L2 today's daily file
TODAY="$(date +%Y-%m-%d)"
DAILY="$MEM_DIR/$TODAY.md"
if [ ! -f "$DAILY" ]; then
  cat > "$DAILY" <<EOF
# Daily memory — $TODAY (L2)

_Append-only log. Rolled into L3 by \`memory-promote.sh\` (2-strike rule)._

## Observations
EOF
  echo "  init $DAILY"
else
  echo "  skip $DAILY (exists)"
fi

# L4 root summary
ROOT="$ARTEFACTS/MEMORY.md"
if [ ! -f "$ROOT" ] || $FORCE; then
  cat > "$ROOT" <<'EOF'
# Memory Index (L4)

_Generated by `memory-promote.sh`. Do not hand-edit — edit the linked layer files instead._

## How to use this file
- This is the **first** file every skill should read before starting a task.
- Drill into L3 only when more detail is needed (`memory/preferences.md`, `memory/system.md`, `memory/projects.md`, `memory/decisions.md`).
- Run `agentic-kit/tools/memory-search.sh "<query>"` for full-text + ranked retrieval across all layers.

## High-confidence preferences
_(empty — populate by running the pipeline; entries promote here after the 2-strike rule)_

## High-confidence system facts
_(empty)_

## Most-referenced decisions (last 90 days)
_(empty)_

## Recent supersessions
_(empty)_
EOF
  echo "  init $ROOT"
else
  echo "  skip $ROOT (exists)"
fi

# Optional migration of legacy SEMANTIC_MEMORY.md
if $MIGRATE && [ -f "$LEGACY_SEMANTIC" ]; then
  echo "  migrating legacy SEMANTIC_MEMORY.md → memory/preferences.md (best effort)…"
  # Append a single block referencing the legacy file. memory-promote.sh
  # will hash + structure it on next run.
  {
    echo ""
    echo "<!-- migrated $(date -u +%Y-%m-%dT%H:%M:%SZ) from SEMANTIC_MEMORY.md -->"
    echo ""
    while IFS= read -r line; do
      [[ "$line" =~ ^- ]] || continue
      printf -- '- id: pending\n  decided: %s\n  entity_type: pattern\n  entities: []\n  confidence: medium\n  source: SEMANTIC_MEMORY.md\n  text: |\n    %s\n' \
        "$(date +%Y-%m-%d)" "${line#- }"
    done < "$LEGACY_SEMANTIC"
  } >> "$MEM_DIR/preferences.md"
  mv "$LEGACY_SEMANTIC" "$LEGACY_SEMANTIC.legacy" 2>/dev/null || true
  echo "  legacy file renamed → SEMANTIC_MEMORY.md.legacy (review and delete when satisfied)"
fi

echo
echo "Memory tree initialised at $MEM_DIR"
echo "Next: run a feature; Zlydni will append to $DAILY automatically."
echo "      Run \`agentic-kit/tools/memory-search.sh '<query>'\` to query across layers."
