#!/usr/bin/env bash
# Probes the project to produce .artefacts/PROJECT_PROFILE.md.
# Usage:  agentic-kit/tools/probe-project.sh [--force] [--quick]
#   --force   Overwrite existing PROJECT_PROFILE.md
#   --quick   Skip the LLM enrichment step (fast, plain heuristics only)
#
# Override the artefacts directory with $ARTEFACTS_DIR.
#
# Detects: language, package manager, test/build commands, frameworks, conventions.
# When `claude` CLI is on PATH and not --quick, it asks for a richer summary.
# Run from the project root.

set -euo pipefail

ARTEFACTS="${ARTEFACTS_DIR:-.artefacts}"
PROFILE_FILE="$ARTEFACTS/PROJECT_PROFILE.md"

FORCE=false
QUICK=false
for _arg in "$@"; do
  case "$_arg" in
    --force) FORCE=true ;;
    --quick) QUICK=true ;;
    -h|--help)
      sed -n '2,9p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
  esac
done

if [ -f "$PROFILE_FILE" ] && [ "$FORCE" = false ]; then
  echo "PROJECT_PROFILE.md already exists. Use --force to overwrite."
  exit 0
fi

mkdir -p "$ARTEFACTS"

# ---------------------------------------------------------------------------
# Heuristics — language / runtime / tooling
# ---------------------------------------------------------------------------
languages=()
package_managers=()
test_cmd=""
build_cmd=""
frameworks=()
test_dirs=()
hot_files=()

[ -f package.json ]      && { languages+=("JavaScript/TypeScript"); package_managers+=("npm/pnpm/yarn (see lockfile)"); hot_files+=("package.json"); }
[ -f pnpm-lock.yaml ]    && package_managers+=("pnpm")
[ -f yarn.lock ]         && package_managers+=("yarn")
[ -f bun.lockb ]         && package_managers+=("bun")
[ -f tsconfig.json ]     && languages+=("TypeScript")
[ -f deno.json ]         && languages+=("Deno")

[ -f pyproject.toml ]    && { languages+=("Python"); package_managers+=("uv/poetry/pip (pyproject.toml)"); hot_files+=("pyproject.toml"); }
[ -f requirements.txt ]  && package_managers+=("pip (requirements.txt)")
[ -f Pipfile ]           && package_managers+=("pipenv")
[ -f setup.cfg ] || [ -f setup.py ] && hot_files+=("$( [ -f setup.cfg ] && echo setup.cfg || echo setup.py )")

[ -f Cargo.toml ]        && { languages+=("Rust"); package_managers+=("cargo"); hot_files+=("Cargo.toml"); }
[ -f go.mod ]            && { languages+=("Go"); package_managers+=("go modules"); hot_files+=("go.mod"); }
[ -f pom.xml ]           && { languages+=("Java"); package_managers+=("maven"); hot_files+=("pom.xml"); }
[ -f build.gradle ] || [ -f build.gradle.kts ] && { languages+=("Java/Kotlin"); package_managers+=("gradle"); }
[ -f Gemfile ]           && { languages+=("Ruby"); package_managers+=("bundler"); }
[ -f composer.json ]     && { languages+=("PHP"); package_managers+=("composer"); }
[ -f Makefile ]          && hot_files+=("Makefile")
[ -f manifest.json ] && grep -q '"manifest_version"' manifest.json 2>/dev/null && frameworks+=("Chrome Extension (MV3 if manifest_version=3)")

# Test/build heuristics from package.json
if [ -f package.json ]; then
  if grep -q '"test"' package.json 2>/dev/null;  then test_cmd="npm test"; fi
  if grep -q '"build"' package.json 2>/dev/null; then build_cmd="npm run build"; fi
fi
[ -f Cargo.toml ] && { test_cmd="${test_cmd:-cargo test}"; build_cmd="${build_cmd:-cargo build}"; }
[ -f go.mod ]     && { test_cmd="${test_cmd:-go test ./...}"; build_cmd="${build_cmd:-go build ./...}"; }
[ -f pyproject.toml ] && { test_cmd="${test_cmd:-pytest}"; build_cmd="${build_cmd:-python -m build}"; }

# Test directories
for d in tests test __tests__ spec specs; do
  [ -d "$d" ] && test_dirs+=("$d")
done

# Frameworks from package.json deps (rough)
if [ -f package.json ]; then
  grep -oE '"(react|next|vue|svelte|angular|express|nestjs|fastify|astro|remix|vite|webpack|rollup|esbuild|jest|vitest|mocha|playwright|cypress|prisma|drizzle|tailwindcss)"' package.json 2>/dev/null \
    | sort -u | tr -d '"' | while read -r f; do echo "$f"; done > "$ARTEFACTS/.probe-fw.tmp" || true
  while IFS= read -r f; do [ -n "$f" ] && frameworks+=("$f"); done < "$ARTEFACTS/.probe-fw.tmp"
  rm -f "$ARTEFACTS/.probe-fw.tmp"
fi

# Top-level layout
top_dirs=$(ls -1 -d */ 2>/dev/null | head -n 30 || true)

# Conventions sniff
indent_style="unknown"
if [ -f .editorconfig ]; then
  if grep -q 'indent_style *= *tab' .editorconfig 2>/dev/null; then indent_style="tab"; fi
  if grep -q 'indent_style *= *space' .editorconfig 2>/dev/null; then indent_style="space"; fi
fi

# ---------------------------------------------------------------------------
# Write base profile
# ---------------------------------------------------------------------------
{
  echo "# Project Profile"
  echo ""
  echo "_Generated by \`agentic-kit/tools/probe-project.sh\` on $(date '+%Y-%m-%d %H:%M:%S'). Re-run with \`--force\` to refresh._"
  echo ""
  echo "## Stack"
  echo "- **Languages:** ${languages[*]:-unknown}"
  echo "- **Package managers:** ${package_managers[*]:-unknown}"
  echo "- **Frameworks/tools:** ${frameworks[*]:-unknown}"
  echo ""
  echo "## Commands (heuristic — verify against PROJECT.md)"
  echo "- **Test:** \`${test_cmd:-<unknown>}\`"
  echo "- **Build:** \`${build_cmd:-<unknown>}\`"
  echo ""
  echo "## Layout"
  echo "- **Top-level dirs:**"
  if [ -n "$top_dirs" ]; then
    while IFS= read -r d; do echo "  - \`$d\`"; done <<<"$top_dirs"
  else
    echo "  - (none detected)"
  fi
  echo "- **Test directories:** ${test_dirs[*]:-none detected}"
  echo "- **Hot files:** ${hot_files[*]:-none detected}"
  echo ""
  echo "## Conventions"
  echo "- **Indent style (.editorconfig):** $indent_style"
  echo ""
  echo "## How agents should use this file"
  echo ""
  echo "Read this file at the start of every task. Treat it as **factual context** about the project, not as a rule book. Cross-check against \`PROJECT.md\` (which the user fills in)."
  echo ""
  echo "- **Vadavik / Lojma / Laznik / Cmok (skill) / Mokash** — read this before producing artefacts to match the project's stack and conventions."
  echo "- **Cmok (build) / Bagnik / Zlydni** — use the commands above as fallback if \`PROJECT.md\` is incomplete."
} > "$PROFILE_FILE"

echo "Wrote $PROFILE_FILE (heuristics)."

# ---------------------------------------------------------------------------
# Optional: LLM enrichment
# ---------------------------------------------------------------------------
if [ "$QUICK" = true ]; then
  exit 0
fi

if ! command -v claude &>/dev/null; then
  echo "claude CLI not on PATH — skipping LLM enrichment. Use --quick to suppress this message."
  exit 0
fi

# Sample some files for the LLM (cap volume)
sample=""
for f in README.md package.json pyproject.toml Cargo.toml go.mod Makefile tsconfig.json .editorconfig; do
  if [ -f "$f" ]; then
    sample+="--- $f ---"$'\n'
    sample+=$(head -n 80 "$f")$'\n\n'
  fi
done

enrich_prompt="You are enriching a project profile for AI development agents.

Below is a heuristic profile already produced and a sample of key project files. Add a single new section titled '## Inferred conventions & priorities' to APPEND to the profile.

Heuristic profile:
---
$(cat "$PROFILE_FILE")
---

Key file samples (truncated):
---
$sample
---

Rules:
- Output ONLY the new markdown section (start with '## Inferred conventions & priorities'). No preamble.
- 5–12 bullets max, specific and actionable.
- Cover: naming style, module boundaries, error handling, testing patterns, doc style, anti-patterns to avoid.
- Skip anything you cannot ground in the samples — silence is better than guessing.
- Do not duplicate facts already in the heuristic profile."

addition=$(claude -p --allowedTools '' "$enrich_prompt" 2>/dev/null || true)

if [ -n "$addition" ]; then
  printf '\n%s\n' "$addition" >> "$PROFILE_FILE"
  echo "Appended LLM-inferred conventions to $PROFILE_FILE."
else
  echo "LLM enrichment returned empty output (skipped)."
fi
